sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t luisfredo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true luisfredo/react-test npm test

after_success:
  - docker build -t luisfredo/multi-client ./client
  - docker build -t luisfredo/multi-nginx ./nginx
  - docker build -t luisfredo/multi-server ./server
  - docker build -t luisfredo/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push luisfredo/multi-client
  - docker push luisfredo/multi-nginx
  - docker push luisfredo/multi-server
  - docker push luisfredo/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket-name: 'elasticbeanstalk-us-east-2-50661650768'
  bucket-path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
